namespace Amazon.Redshift;

[TestClass]
public sealed class DataType_Parse : ParseTestBase
{
    [TestMethod]
    [DataRow("BIGINT")]
    [DataRow("BINARY VARYING")]
    [DataRow("BOOL")]
    [DataRow("BOOLEAN")]
    [DataRow("BPCHAR")]
    [DataRow("CHAR")]
    [DataRow("CHAR(22)")]
    [DataRow("CHARACTER")]
    [DataRow("CHARACTER(22)")]
    [DataRow("CHARACTER VARYING")]
    [DataRow("CHARACTER VARYING(22)")]
    [DataRow("DATE")]
    [DataRow("DECIMAL")]
    [DataRow("DECIMAL(18)")]
    [DataRow("DECIMAL(18,2)")]
    [DataRow("DOUBLE PRECISION")]
    [DataRow("FLOAT")]
    [DataRow("FLOAT(48)")]
    [DataRow("FLOAT4")]
    [DataRow("FLOAT8")]
    [DataRow("GEOGRAPHY")]
    [DataRow("GEOMETRY")]
    [DataRow("HLLSKETCH")]
    [DataRow("INT")]
    [DataRow("INT2")]
    [DataRow("INT4")]
    [DataRow("INT8")]
    [DataRow("INTEGER")]
    [DataRow("INTERVAL DAY TO SECOND (7)")]
    [DataRow("INTERVAL YEAR TO MONTH")]
    [DataRow("NATIONAL CHARACTER")]
    [DataRow("NATIONAL CHARACTER(22)")]
    [DataRow("NATIONAL CHARACTER VARYING")]
    [DataRow("NATIONAL CHARACTER VARYING(22)")]
    [DataRow("NCHAR")]
    [DataRow("NCHAR(22)")]
    [DataRow("NUMERIC")]
    [DataRow("NUMERIC(18)")]
    [DataRow("NUMERIC(18,2)")]
    [DataRow("NVARCHAR")]
    [DataRow("NVARCHAR(22)")]
    [DataRow("REAL")]
    [DataRow("SMALLINT")]
    [DataRow("SUPER")]
    [DataRow("TEXT")]
    [DataRow("TIME")]
    [DataRow("TIME WITH TIME ZONE")]
    [DataRow("TIME WITHOUT TIME ZONE")]
    [DataRow("TIMESTAMP")]
    [DataRow("TIMESTAMP WITH TIME ZONE")]
    [DataRow("TIMESTAMP WITHOUT TIME ZONE")]
    [DataRow("TIMESTAMPTZ")]
    [DataRow("TIMETZ")]
    [DataRow("VARBINARY")]
    [DataRow("VARBYTE")]
    [DataRow("VARBYTE(22)")]
    [DataRow("VARCHAR")]
    [DataRow("VARCHAR(22)")]
    public void DataType(string fragment)
    {
        Parse(fragment);
    }
}