<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Visitors\**" />
    <Compile Remove="Writers\**" />
    <EmbeddedResource Remove="Visitors\**" />
    <EmbeddedResource Remove="Writers\**" />
    <None Remove="Visitors\**" />
    <None Remove="Writers\**" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="DuckDBParser.g4">
      <Package>DuckDB</Package>
      <Listener>False</Listener>
      <Visitor>True</Visitor>
      <Error>True</Error>
    </Antlr4>
    <Antlr4 Include="DuckDBLexer.g4">
      <Package>DuckDB</Package>
      <Listener>False</Listener>
      <Visitor>True</Visitor>
      <Error>True</Error>
    </Antlr4>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Visitors\BatchVisitor.cs" />
    <Compile Include="Visitors\Identifiers\FunctionNameVisitor.cs" />
    <Compile Include="Visitors\Identifiers\IdentifierVisitor.cs" />
    <Compile Include="Visitors\Identifiers\IndexNameVisitor.cs" />
    <Compile Include="Visitors\Identifiers\SchemaNameVisitor.cs" />
    <Compile Include="Visitors\Identifiers\SequenceNameVisitor.cs" />
    <Compile Include="Visitors\Identifiers\TableNameVisitor.cs" />
    <Compile Include="Visitors\Identifiers\TypeNameVisitor.cs" />
    <Compile Include="Visitors\Identifiers\ViewNameVisitor.cs" />
    <Compile Include="Visitors\SqlVisitor.C.cs" />
    <Compile Include="Visitors\SqlVisitor.cs" />
    <Compile Include="Visitors\SqlVisitor.D.cs" />
    <Compile Include="Visitors\SqlVisitor.F.cs" />
    <Compile Include="Visitors\SqlVisitor.I.cs" />
    <Compile Include="Visitors\SqlVisitor.O.cs" />
    <Compile Include="Visitors\SqlVisitor.S.cs" />
    <Compile Include="Visitors\SqlVisitor.T.cs" />
    <Compile Include="Visitors\SqlVisitor.V.cs" />
    <Compile Include="Visitors\Statements\CascadeRestrictVisitor.cs" />
    <Compile Include="Visitors\Statements\DropFunctionVisitor.cs" />
    <Compile Include="Visitors\Statements\DropIndexVisitor.cs" />
    <Compile Include="Visitors\Statements\DropSchemaVisitor.cs" />
    <Compile Include="Visitors\Statements\DropSequenceVisitor.cs" />
    <Compile Include="Visitors\Statements\DropTableVisitor.cs" />
    <Compile Include="Visitors\Statements\DropTypeVisitor.cs" />
    <Compile Include="Visitors\Statements\DropViewVisitor.cs" />
    <Compile Include="Visitors\Statements\DropVisitor.cs" />
    <Compile Include="Visitors\Statements\OtherVisitor.cs" />
    <Compile Include="Visitors\Statements\StatementTerminationVisitor.cs" />
    <Compile Include="Visitors\Statements\StatementVisitor.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tradurre\Tradurre.csproj" />
  </ItemGroup>

</Project>