lexer grammar RedshiftLexer;

channels { comment, whitespace }
options { caseInsensitive = true; }

ABORT : 'ABORT';
ACCOUNT : 'ACCOUNT';
AES128 : 'AES128';
AES256 : 'AES256';
ALL : 'ALL';
ALLOWOVERWRITE : 'ALLOWOVERWRITE';
ANALYSE : 'ANALYSE';
ANALYZE : 'ANALYZE';
AND : 'AND';
ANY : 'ANY';
ARRAY : 'ARRAY';
AS : 'AS';
ASC : 'ASC';
ATTACH : 'ATTACH';
AUTHORIZATION : 'AUTHORIZATION';
AUTO : 'AUTO';
AZ64 : 'AZ64';

BACKUP : 'BACKUP';
BETWEEN : 'BETWEEN';
BIGINT : 'BIGINT';
BINARY : 'BINARY';
BINDING : 'BINDING';
BLANKSASNULL : 'BLANKSASNULL';
BOOL : 'BOOL' ;
BOOLEAN : 'BOOLEAN' ;
BOOST : 'BOOST';
BOTH : 'BOTH';
BPCHAR : 'BPCHAR' ;
BY : 'BY';
BYTEDICT : 'BYTEDICT';
BZIP2 : 'BZIP2';

CALL : 'CALL';
CANCEL : 'CANCEL';
CASCADE : 'CASCADE';
CASE : 'CASE';
CASE_INSENSITIVE : 'CASE_INSENSITIVE';
CASE_SENSITIVE : 'CASE_SENSITIVE';
CAST : 'CAST';
CHAR : 'CHAR' ;
CHARACTER : 'CHARACTER' ;
CHECK : 'CHECK';
CI : 'CI';
CLOSE : 'CLOSE';
COLLATE : 'COLLATE';
COLUMN : 'COLUMN';
COLUMNS : 'COLUMNS';
COMMENT : 'COMMENT';
COMMIT : 'COMMIT';
COMPOUND : 'COMPOUND';
COMPRESSION : 'COMPRESSION';
COMPROWS : 'COMPROWS';
CONSTRAINT : 'CONSTRAINT';
CREATE : 'CREATE';
CREDENTIALS : 'CREDENTIALS';
CROSS : 'CROSS';
CS : 'CS';
CURRENT_DATE : 'CURRENT_DATE';
CURRENT_TIME : 'CURRENT_TIME';
CURRENT_TIMESTAMP : 'CURRENT_TIMESTAMP';
CURRENT_USER : 'CURRENT_USER';
CURRENT_USER_ID : 'CURRENT_USER_ID';
CURSOR : 'CURSOR';

DATABASE : 'DATABASE';
DATASHARE : 'DATASHARE';
DATE : 'DATE' ;
DAY : 'DAY';
DEALLOCATE : 'DEALLOCATE';
DECIMAL : 'DECIMAL' ;
DECLARE : 'DECLARE';
DEFAULT : 'DEFAULT';
DEFAULTS : 'DEFAULTS';
DEFERRABLE : 'DEFERRABLE';
DEFLATE : 'DEFLATE';
DEFRAG : 'DEFRAG';
DELETE : 'DELETE';
DELTA : 'DELTA';
DELTA32K : 'DELTA32K';
DESC : 'DESC';
DETACH : 'DETACH';
DISABLE : 'DISABLE';
DISTINCT : 'DISTINCT';
DISTKEY : 'DISTKEY ';
DISTSTYLE : 'DISTSTYLE';
DO : 'DO';
DOUBLE : 'DOUBLE' ;
DROP : 'DROP' ;

ELSE : 'ELSE';
EMPTYASNULL : 'EMPTYASNULL';
ENABLE : 'ENABLE';
ENCODE : 'ENCODE';
ENCRYPT      : 'ENCRYPT     ';
ENCRYPTION : 'ENCRYPTION';
END : 'END';
EVEN : 'EVEN';
EXCEPT : 'EXCEPT';
EXCLUDING : 'EXCLUDING';
EXECUTE : 'EXECUTE';
EXISTS : 'EXISTS';
EXPLAIN : 'EXPLAIN';
EXPLICIT : 'EXPLICIT';
EXTERNAL : 'EXTERNAL';
EXTERNALID : 'EXTERNALID';

FALSE : 'FALSE';
FETCH : 'FETCH';
FLOAT : 'FLOAT' ;
FLOAT4 : 'FLOAT4' ;
FLOAT8 : 'FLOAT8' ;
FOR : 'FOR';
FORCE : 'FORCE';
FOREIGN : 'FOREIGN';
FORWARD : 'FORWARD';
FREEZE : 'FREEZE';
FROM : 'FROM';
FULL : 'FULL';
FUNCTION : 'FUNCTION';

GEOGRAPHY : 'GEOGRAPHY' ;
GEOMETRY : 'GEOMETRY' ;
GENERATED : 'GENERATED';
GLOBALDICT256 : 'GLOBALDICT256';
GLOBALDICT64K : 'GLOBALDICT64K';
GRANT : 'GRANT';
GROUP : 'GROUP';
GZIP : 'GZIP';

HAVING : 'HAVING';
HLLSKETCH : 'HLLSKETCH' ;

IDENTITY : 'IDENTITY';
IF : 'IF';
IGNORE : 'IGNORE';
ILIKE : 'ILIKE';
IN : 'IN';
INCLUDING : 'INCLUDING';
INITIALLY : 'INITIALLY';
INNER : 'INNER';
INSERT : 'INSERT';
INT : 'INT' ;
INT2 : 'INT2' ;
INT4 : 'INT4' ;
INT8 : 'INT8' ;
INTEGER : 'INTEGER' ;
INTERLEAVED : 'INTERLEAVED';
INTERSECT : 'INTERSECT';
INTERVAL : 'INTERVAL';
INTO : 'INTO';
IS : 'IS';
ISNULL : 'ISNULL';

JOIN : 'JOIN';

KEY : 'KEY';

LEADING : 'LEADING';
LEFT : 'LEFT';
LIBRARY : 'LIBRARY';
LIKE : 'LIKE';
LIMIT : 'LIMIT';
LOCAL : 'LOCAL';
LOCALTIME : 'LOCALTIME';
LOCALTIMESTAMP : 'LOCALTIMESTAMP';
LOCK : 'LOCK';
LUN : 'LUN';
LUNS : 'LUNS';
LZO : 'LZO';
LZOP : 'LZOP';

MASKING : 'MASKING';
MATERIALIZED : 'MATERIALIZED';
MERGE : 'MERGE';
MINUS : 'MINUS';
MODEL : 'MODEL';
MONTH : 'MONTH';
MOSTLY16 : 'MOSTLY16';
MOSTLY32 : 'MOSTLY32';
MOSTLY8 : 'MOSTLY8';

NAMESPACE : 'NAMESPACE';
NATIONAL : 'NATIONAL';
NATURAL : 'NATURAL';
NCHAR : 'NCHAR' ;
NEW : 'NEW';
NEXT : 'NEXT';
NO : 'NO';
NOT : 'NOT';
NOTNULL : 'NOTNULL';
NULL : 'NULL';
NULLS : 'NULLS';
NUMERIC : 'NUMERIC' ;
NVARCHAR : 'NVARCHAR' ;

OF : 'OF';
OFF : 'OFF';
OFFLINE : 'OFFLINE';
OFFSET : 'OFFSET';
OID : 'OID';
OLD : 'OLD';
ON : 'ON';
ONLY : 'ONLY';
OPEN : 'OPEN';
OR : 'OR';
ORDER : 'ORDER';
OUTER : 'OUTER';
OVERLAPS : 'OVERLAPS';

PARALLEL : 'PARALLEL';
PARTITION : 'PARTITION';
PERCENT : 'PERCENT';
PERMISSIONS : 'PERMISSIONS';
PIVOT : 'PIVOT';
PLACING : 'PLACING';
POLICY : 'POLICY';
PRECISION : 'PRECISION';
PREDICATE : 'PREDICATE';
PREPARE : 'PREPARE';
PRIMARY : 'PRIMARY';
PROCEDURE : 'PROCEDURE';
PROVIDER : 'PROVIDER';
PUBLIC : 'PUBLIC';
PUBLICACCESSIBLE : 'PUBLICACCESSIBLE';

RAW : 'RAW';
READRATIO : 'READRATIO';
REAL : 'REAL' ;
RECLUSTER : 'RECLUSTER';
RECOVER : 'RECOVER';
REFERENCES : 'REFERENCES';
REFRESH : 'REFRESH';
REINDEX : 'REINDEX';
REJECTLOG : 'REJECTLOG';
REPLACE : 'REPLACE';
RESORT : 'RESORT';
RESPECT : 'RESPECT';
RESET : 'RESET';
RESTRICT : 'RESTRICT';
RESTORE : 'RESTORE';
REVOKE : 'REVOKE';
RIGHT : 'RIGHT';
RLS : 'RLS';
ROLE : 'ROLE';
ROLLBACK : 'ROLLBACK';
RUNLENGTH : 'RUNLENGTH';

SCHEMA : 'SCHEMA';
SECOND : 'SECOND';
SELECT : 'SELECT';
SESSION : 'SESSION' ;
SESSION_USER : 'SESSION_USER';
SET : 'SET' ;
SIMILAR : 'SIMILAR';
SMALLINT : 'SMALLINT' ;
SNAPSHOT  : 'SNAPSHOT ';
SOME : 'SOME';
SORT : 'SORT';
SORTKEY : 'SORTKEY';
SUPER : 'SUPER' ;
SYSDATE : 'SYSDATE';
SYSTEM : 'SYSTEM';

TABLE : 'TABLE';
TAG : 'TAG';
TDES : 'TDES';
TEMP : 'TEMP';
TEMPORARY : 'TEMPORARY';
TEXT : 'TEXT' ;
TEXT255 : 'TEXT255';
TEXT32K : 'TEXT32K';
THEN : 'THEN';
TIME : 'TIME' ;
TIMESTAMP : 'TIMESTAMP' ;
TIMESTAMPTZ : 'TIMESTAMPTZ' ;
TIMETZ : 'TIMETZ' ;
TO : 'TO';
TOP : 'TOP';
TRAILING : 'TRAILING';
TRANSACTION : 'TRANSACTION';
TRUE : 'TRUE';
TRUNCATE : 'TRUNCATE';
TRUNCATECOLUMNS : 'TRUNCATECOLUMNS';

UNION : 'UNION';
UNIQUE : 'UNIQUE';
UNNEST : 'UNNEST';
UNPIVOT : 'UNPIVOT';
USE : 'USE';
USER : 'USER';
USING : 'USING';

VACUUM : 'VACUUM';
VALUES : 'VALUES';
VARBINARY : 'VARBINARY' ;
VARBYTE : 'VARBYTE' ;
VARCHAR : 'VARCHAR';
VARYING : 'VARYING';
VERBOSE : 'VERBOSE';
VIEW : 'VIEW';

WALLET : 'WALLET';
WHEN : 'WHEN';
WHERE : 'WHERE';
WITH : 'WITH';
WITHOUT : 'WITHOUT';
WORK : 'WORK';

YEAR : 'YEAR';
YES : 'YES';

ZONE : 'ZONE';
ZSTD : 'ZSTD';

COMMENT_MULTI_LINE : '/*' (.)*? '*/' -> channel(comment) ;
COMMENT_SINGLE_LINE : '--' ~[\r\n]* -> channel(comment) ;

WHITE_SPACE : [ \r\n\t]+ -> channel(whitespace);

AMPERSAND : '&' ;
AMPERSAND_EQUALS : '&=' ;
ASTERISK : '*' ;
BRACKET_L : '[' ;
BRACKET_R : ']' ;
COLON : ':' ;
COMMA : ',' ;
MINUS_ : '-' ;
PAREN_L : '(' ;
PAREN_R : ')' ;
PARENS : '()' ;
PERCENT_ : '%' ;
PERIOD_ : '.' ;
PLUS : '+' ;
SEMICOLON : ';' ;
SLASH : '/' ;

EQ : '=' ;
NEQ : '<>' | '!=' ;
GT : '>' ;
GTE : '>=' ;
NGT : '!>' ;
LT : '<' ;
LTE : '<=' ;
NLT : '!<' ;

DOUBLE_QUOTED_IDENTIFER : '"' ( '""' | ~'"' )* '"';
INTEGER_IDENTIFIER : ( '+' | '-' )? [0-9]+;
FLOATING_POINT_IDENTIFIER : ( '+' | '-' )? [0-9]+ '.'? [0-9]* ( 'E' ( '+' | '-' )? [0-9]+ )?;
SINGLE_QUOTED_IDENTIFER : '\'' ( '\'\'' | ~'\'' )* '\'';
IDENTIFIER : ( [A-Z_] | F_MULTIBYTE_CHARACTERS ) ( [A-Z0-9_$] | F_MULTIBYTE_CHARACTERS )*;

// Fragments
fragment F_PLUS_MINUS : '+' | '-';
fragment F_DIGIT : [0-9];
fragment F_MULTIBYTE_CHARACTERS options { caseInsensitive = false; }:
    '\u0080' .. '\u07ff'
    | '\u0800' .. '\uffff'
    | '\u{10000}' .. '\u{10FFFF}'
   ;

UNRECOGNIZED : .;