parser grammar RedshiftParser;

options { tokenVocab=RedshiftLexer; }

batch : statement+ EOF;

statement
    : abort
    // TODO: | alter
    | analyze
    | analyze_compression
    | attach_masking_policy
    | attach_rls_policy

    // TODO: | begin

    | call
    | cancel
    | close
    | comment
    | commit
    // TODO: | copy
    | create

    | deallocate
    | declare
    // TODO: | delete
    | desc_datashare
    | desc_identity_provider
    | detach_masking_policy
    | detach_rls_policy
    | drop

    | end
    | execute
    | explain

    | fetch
    
    | grant

    | insert

    | lock

    | merge

    | prepare

    | refresh_materialized_view
    | reset
    | revoke
    | rollback

    // TODO: | select
    // TODO: | select_into
    // TODO: | set
    | set_session_authorization

    | termination
    | truncate

    | use

    | vacuum
    ;


abort : ABORT ( TRANSACTION | WORK ) ;
analyze : ANALYZE VERBOSE? ( table_name column_name_list )? ( ( PREDICATE COLUMNS ) | ( ALL  COLUMNS ))? ;
analyze_compression : ANALYZE COMPRESSION ( table_name column_name_list? )? ( COMPROWS numrows=INTEGER_IDENTIFIER) ;
attach_masking_policy : ATTACH MASKING POLICY policy_name ON relation_name ; // TODO: Finish
attach_rls_policy : ATTACH RLS POLICY policy_name ON TABLE? table_name ( ',' table_name )* TO ( user_name | ( ROLE role_name ) | PUBLIC ) ( ',' ( user_name | ( ROLE role_name ) | PUBLIC ) )* ;

// TODO: begin: BEGIN ;

call : CALL procedure_name ; // TODO: Finish ( '(' argument ( ',' argument) ')')? ;
cancel : CANCEL process_id=INTEGER_IDENTIFIER message=SINGLE_QUOTED_IDENTIFER? ;
close : CLOSE cursor_name ;
comment : COMMENT ON 
    (
        COLUMN column_name
        CONSTRAINT constraint_name ON table_name
        DATABASE database_name
        TABLE table_name
        VIEW view_name
    )
    IS ( SINGLE_QUOTED_IDENTIFER | NULL )
    ;
commit : COMMIT ( TRANSACTION | WORK ) ;
// TODO: copy : ;

create
    : create_database
    | create_datashare
    | create_external_function
    
    
    | create_role
    | create_table
    
    | create_view
    ;

create_database : CREATE DATABASE database_name ; // TODO:
create_datashare : CREATE DATASHARE datashare_name ( SET? PUBLICACCESSIBLE '='? ( TRUE | FALSE ) )? ;
create_external_function : CREATE or_replace? EXTERNAL FUNCTION function_name '(' ( data_type (',' data_type )* ) ')' ;
create_role : CREATE ROLE role_name ( EXTERNALID external_id=DOUBLE_QUOTED_IDENTIFER )? ;

create_table : CREATE ( LOCAL? ( TEMP | TEMPORARY ))? TABLE if_not_exists? table_name
    '(' column_definition ( ',' column_definition )* ')'
    ( BACKUP ( YES | NO ) ) ?
    table_attribute*
    ;

column_attribute
    :
    ( DEFAULT expression )
    | ( IDENTITY '(' seed=INTEGER_IDENTIFIER ',' step=INTEGER_IDENTIFIER ')' )
    | ( GENERATED BY DEFAULT AS IDENTITY '(' seed=INTEGER_IDENTIFIER ',' step=INTEGER_IDENTIFIER ')' )
    | ( ENCODE encoding )
    | DISTKEY
    | SORTKEY
    | ( COLLATE ( CASE_SENSITIVE | CS | CASE_INSENSITIVE | CI ) )
    ;

column_constraint
    : null_not_null
    | ( ( PRIMARY KEY ) | UNIQUE )
    | ( REFERENCES reftable=table_name ( '(' refcolumn=column_name ')' )? )
    ;


column_definition
    : ( column_name data_type ( column_attribute | column_constraint )* )
    | table_constraint
    | ( LIKE parent_table=table_name ( ( EXCLUDING | INCLUDING ) DEFAULTS )? )
    ;

encoding
    : AZ64
    | BYTEDICT
	| DELTA
	| DELTA32K
	| LZO
	| MOSTLY8
	| MOSTLY16
	| MOSTLY32
	| RAW
	| RUNLENGTH
	| TEXT255
	| TEXT32K
	| ZSTD
    ;

table_attribute
    : ( DISTSTYLE ( AUTO | EVEN | KEY | ALL ) )
    | ( DISTKEY '(' column_name ')' ) 
    | ( ( COMPOUND | INTERLEAVED )? SORTKEY column_name_list ( SORTKEY AUTO )? )
    | ( ENCODE AUTO )
    ;

table_constraint
    : ( UNIQUE column_name_list )
    | ( PRIMARY KEY column_name_list )
    | ( FOREIGN KEY column_name_list REFERENCES table_name )
    ;

column_name_list : '(' column_name ( ',' column_name )* ')' ;

create_view : CREATE or_replace? VIEW view_name ( column_name_list )? AS select ( WITH NO SCHEMA BINDING )? ; // TODO: 

deallocate :  DEALLOCATE PREPARE? plan_name ;
declare : DECLARE cursor_name CURSOR FOR ; // TODO: select ;
// TODO: delete : ;
desc_datashare : DESC DATASHARE datashare_name ( OF  ( ACCOUNT account_id=SINGLE_QUOTED_IDENTIFER )? NAMESPACE namespace_guid=SINGLE_QUOTED_IDENTIFER )? ;
desc_identity_provider : DESC IDENTITY PROVIDER identity_provider_name ;
detach_masking_policy : DETACH MASKING POLICY policy_name ON table_name column_name_list FROM ( user_name | ( ROLE role_name ) | PUBLIC ) ;
detach_rls_policy : DETACH RLS POLICY policy_name ON TABLE? table_name ( ',' table_name )* FROM ( user_name | ( ROLE role_name ) | PUBLIC ) ( ',' ( user_name | ( ROLE role_name ) | PUBLIC ) )* ;
drop
    : drop_database
    | drop_datashare
    | drop_external_view
    | drop_function
    | drop_group
    | drop_identity_provider
    | drop_masking_policy
    | drop_materialized_view
    | drop_model
    | drop_procedure
    | drop_role
    | drop_schema
    | drop_table
    | drop_user
    | drop_view
    ;

drop_database : DROP DATABASE database_name FORCE? ;
drop_datashare : DROP DATASHARE datashare_name ;
drop_external_view : DROP EXTERNAL VIEW view_name if_exists? ;
drop_function : DROP FUNCTION function_name ; // TODO: ;
drop_group : DROP GROUP group_name ;
drop_identity_provider : DROP IDENTITY PROVIDER identity_provider_name CASCADE? ;
drop_library : DROP LIBRARY library_name ;
drop_masking_policy : DROP MASKING POLICY policy_name ;
drop_materialized_view : DROP MATERIALIZED VIEW if_exists? view_name cascade_restrict? ;
drop_model : DROP MODEL if_exists? model_name ;
drop_procedure : DROP PROCEDURE procedure_name ; // TODO: ( [ [ argname ] [ argmode ] argtype [, ...] ] )
drop_rls_policy : DROP RLS POLICY if_exists? policy_name cascade_restrict? ;
drop_role : DROP ROLE role_name ( FORCE | RESTRICT )? ;
drop_schema : DROP SCHEMA if_exists? schema_name ( ',' schema_name )* ( DROP EXTERNAL DATABASE )? cascade_restrict? ;
drop_table : DROP TABLE if_exists? table_name ( ',' table_name )*  cascade_restrict ;
drop_user : DROP USER if_exists? user_name ( ',' user_name )* ;
drop_view : DROP VIEW if_exists? view_name ( ',' view_name )* cascade_restrict? ;

end : END ( TRANSACTION | WORK );
execute : EXECUTE plan_name ; // TODO: ( parameters )?;
explain: EXPLAIN VERBOSE ; // TODO: query ;

fetch : FETCH ( NEXT | ALL | ( FORWARD ( count=INTEGER_IDENTIFIER | ALL ) ) )?;

grant : GRANT ; //TODO:

insert : INSERT INTO table_name column_name_list?
    (
        ( DEFAULT VALUES )
        | ( VALUES 
        
            ( '(' ( DEFAULT | expression ) ( ',' ( DEFAULT | expression ) )* ')' ) ( ',' ( '(' ( DEFAULT | expression ) ( ',' ( DEFAULT | expression ) )* ')' ) )*
            // TODO :| select
        )
    )
    ;

lock : LOCK TABLE? table_name ( ',' table_name )* ;

merge : MERGE INTO table_name USING table_name ; // TODO:

prepare : PREPARE plan_name ; // TODO: 

refresh_materialized_view : REFRESH MATERIALIZED VIEW view_name cascade_restrict? ;
reset : RESET ; // TODO: ( ALL | parameter_name | variable_name ) ;
revoke :  REVOKE ; // TODO
rollback : ROLLBACK ( TRANSACTION | WORK )? ;

select : SELECT ; // TODO ;
// TODO: select_into : ;
// TODO: set: ;
set_session_authorization : SET LOCAL? SESSION AUTHORIZATION ( DEFAULT | user_name ) ;
// NOTE: Deprecated set_session_characteristics : SET SESSION CHARACTERISTICS ;
// TODO: show : ;
// TODO: show_columns :;
// TODO: show_external_table : ;
// TODO: shwo_databases :;
// TODO: show_datashares : ;
// TODO: show_grants : ;
// TODO: show_models :;
// TODO: show_procedures :;
// TODO: show_schemas :;
// TODO: show_table : ;
// TODO: show_tables :;
// TODO: show_view
// NOTE: Deprecated start_transaction :;

termination : ';' ;
truncate : TRUNCATE TABLE? table_name ;

// TODO: unload :;
// TODO: update :;
use : USE database_name ;

vacuum : VACUUM ( FULL | ( DELETE ONLY ) | RECLUSTER | REINDEX | ( SORT ONLY ) )? ( table_name ( TO threshold=INTEGER_IDENTIFIER PERCENT )? BOOST? )? ;



cascade_restrict : CASCADE | RESTRICT ;
constant
    : INTEGER_IDENTIFIER
    | SINGLE_QUOTED_IDENTIFER
    ;

data_type
    : BIGINT
    | ( BINARY VARYING )
    | BOOL
    | BOOLEAN
    | BPCHAR
    | ( CHAR precision? )
    | ( CHARACTER precision? )
    | ( CHARACTER VARYING precision? )
    | DATE
    | ( DECIMAL precision_scale? )
    | ( DOUBLE PRECISION )
    | ( FLOAT precision? )
    | FLOAT4
    | FLOAT8
    | GEOGRAPHY
    | GEOMETRY
    | HLLSKETCH
    | INT
    | INT2
    | INT4
    | INT8
    | INTEGER
    | ( INTERVAL DAY TO SECOND precision? )
    | ( INTERVAL YEAR TO MONTH )
    | ( NATIONAL CHARACTER precision? )
    | ( NATIONAL CHARACTER VARYING precision? )
    | ( NCHAR precision? )
    | ( NUMERIC precision_scale? )
    | ( NVARCHAR precision? )
    | REAL
    | SMALLINT
    | SUPER
    | TEXT
    | TIME
    | ( TIME WITH TIME ZONE )
    | ( TIME WITHOUT TIME ZONE )
    | TIMESTAMP
    | ( TIMESTAMP WITH TIME ZONE )
    | ( TIMESTAMP WITHOUT TIME ZONE )
    | TIMESTAMPTZ
    | TIMETZ
    | VARBINARY
    | ( VARBYTE precision? )
    | ( VARCHAR precision? )
    ;

precision : '(' INTEGER_IDENTIFIER ')' ;
precision_scale : '(' p=INTEGER_IDENTIFIER ( ',' s=INTEGER_IDENTIFIER )? ')' ;

identifier :
    IDENTIFIER
    | DOUBLE_QUOTED_IDENTIFER
    ;

expression
    : constant
    | expression_parens
    //| ( expression operator expression )
    ;

expression_parens : '(' expression ')' ;

if_exists : IF EXISTS ;
if_not_exists : IF NOT EXISTS ;
null_not_null : NOT? NULL ;
operator : '+' | '-' ;// TODO: | '^' | '|/' | '||/' ;
or_replace : OR REPLACE ;

column_name : name=identifier ;
constraint_name : name=identifier ; // TODO: Validate this aginst CREATE CONSTRAINT.
cursor_name : name=identifier ; // TODO: Validate this aginst create cursor.
database_name : name=identifier ;
datashare_name : name=identifier ;
function_name : name=identifier ; // TODO: Validate this aginst CREATE FUNCTION.
group_name : name=identifier ; // TODO: Validate this aginst CREATE GROUP.
identity_provider_name : name=identifier ; // TODO: Validate this aginst CREATE ???.
library_name : name=identifier ; // TODO: Validate this aginst CREATE LIBRARY.
model_name : name=identifier ; // TODO: Validate this aginst CREATE MODEL.
plan_name : name=identifier ; // TODO: Validate against DEALLOCATE.
policy_name : name=identifier ;
procedure_name : name=identifier ; // TODO: Validate this aginst CREATE PROCEDURE.
relation_name : name=identifier ;
role_name : name=identifier ; // TODO: Validate this aginst CREATE ROLE.
schema_name : name=identifier ; // TODO: Validate this aginst CREATE SCHEMA.
table_name : name=identifier ; // TODO: Validate this aginst CREATE TABLE.
user_name : name=identifier ; // TODO: Validate this aginst CREATE USER.
view_name : name=identifier ; // TODO: Validate this aginst CREATE VIEW.
