<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Visitors\**" />
    <Compile Remove="Writers\**" />
    <EmbeddedResource Remove="Visitors\**" />
    <EmbeddedResource Remove="Writers\**" />
    <None Remove="Visitors\**" />
    <None Remove="Writers\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="SqlServerParser.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="TSqlLexer.g4" />
    <None Remove="TSqlParser.g4" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="TSqlLexer.g4">
      <Package>Microsoft.SqlServer</Package>
      <Listener>False</Listener>
      <Visitor>False</Visitor>
    </Antlr4>
    <Antlr4 Include="TSqlParser.g4">
      <Package>Microsoft.SqlServer</Package>
      <Listener>False</Listener>
      <Visitor>True</Visitor>
    </Antlr4>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Writers\SqlWriter.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tradurre\Tradurre.csproj" />
  </ItemGroup>

</Project>